language: shell
before_install:
  - sudo add-apt-repository -y ppa:openscad/releases
  - sudo apt-get -qq update
  - sudo apt-get install -y openscad
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 0.1; done
  - make clean
script: make
