language: shell
before_install:
  - sudo add-apt-repository -y ppa:openscad/releases
  - sudo apt-get -qq update
  - sudo apt-get install -y openscad
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - inotifywait /tmp/.X11-unix | grep --quiet '/tmp/.X11-unix/ CREATE X99'
  - make clean
script: make
